name: "Run Tests"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: "Install PDM"
        run: |
          python -m pip install pdm

      - name: "Install Dependencies"
        run: |
          pdm sync -G dev

      - name: "Run Tests"
        run: make test
