name: "Continuous Integration Workflow"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.3.4

      - name: "Run Tests"
        run: make test
